### ISSUE TITLE
Lag lors du chargement des textures

### ISSUE THREAD

**Issue by Aleweadan** [FXServer-ESX/fxserver-skinchanger#1]
Il y a des lags lors du chargements des textures lorsqu'on change de coupe ou barbe par exemple sa freeze le jeu un peu

**Comment by indilo53** [comment]
Oui je suis au courant ca viens de la fonction de refresh du menu. Je travaille actuellement sur le policejob, je jetterais un oeil après.

**Comment by Aleweadan** [comment]
ok merci :)

**Comment by indilo53** [comment]
Fixé => Il faut télécharger les nouvelles versions de es_extended et esx_skin

**Comment by Aleweadan** [comment]
Merci !
